# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{resque-multiple-failure-backend}
  s.version = "1.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Adam Holt"]
  s.date = %q{2010-11-30}
  s.description = %q{Individual failed queue for each queue you have}
  s.email = %q{Ads.noob@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.mdown"
  ]
  s.files = [
    "Gemfile",
     "Gemfile.lock",
     "LICENSE",
     "README.mdown",
     "Rakefile",
     "VERSION",
     "lib/resque/failure/multiple_failure.rb",
     "lib/resque/failure_server.rb",
     "lib/resque/server/views/failure_queue.erb",
     "lib/resque/server/views/failures.erb",
     "test/helper.rb",
     "test/test_resque-multiple-failure-backend.rb"
  ]
  s.homepage = %q{http://github.com/omgitsads/resque-multiple-failure-backend}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Adds a failed queue for each queue}
  s.test_files = [
    "test/helper.rb",
     "test/test_resque-multiple-failure-backend.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_runtime_dependency(%q<resque>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_dependency(%q<resque>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    s.add_dependency(%q<resque>, [">= 0"])
  end
end

